name: Update GitHub Stats
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: |
        npm install
    - name: Update README
      run: |
        npx github-readme-stats --username USERNAME --token $PAT_1
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update GitHub stats"
        git push
env:
  PAT_1: ${{ secrets.PAT_1 }}
